# ═══════════════════════════════════════════════════════
# المرحلة F4 — Content Creator Capability (الجزء 1/3)
# ═══════════════════════════════════════════════════════
cat > src/world/ContentCreatorCapability_part1.tsx << 'ENDOFFILE'
import React, { useState, useEffect, useCallback } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, ScrollView } from 'react-native';
import Animated, { FadeIn, FadeOut } from 'react-native-reanimated';
import { EventBus } from '../core/EventBus';
import { memoryEngine } from '../../engine/memory/MemoryEngine';
import { capabilityResolver } from '../coordinators/CapabilityResolver';
import { consciousnessCoordinator } from '../coordinators/ConsciousnessCoordinator';
import { sendMessage } from '../services/twinApi';
import { useRTL } from '../utils/useRTL';
import { SPACE, RADIUS } from '../../src/design/tokens/spacing';
import { 
  PenTool, Edit3, Search, TrendingUp, 
    MessageSquare, BookOpen, Camera, Calendar,
      Sparkles, ChevronRight, Brain, Clock, Filter
      } from 'lucide-react-native';
      
      interface CreatorSession {
        id: string;
          title: string;
            type: string;
              content: string;
                timestamp: string;
                }
                
                const CREATOR_CATEGORIES = [
                  {
                      id: 'writing', icon: PenTool, color: '#8B5CF6',
                          label_ar: 'كتابة', label_en: 'Writing',
                              actions: [
                                    { type: 'outline', label_ar: 'مخطط', label_en: 'Outline', placeholder_ar: 'عنوان المقال...', placeholder_en: 'Article title...', icon: BookOpen },
                                          { type: 'write', label_ar: 'كتابة', label_en: 'Write', placeholder_ar: 'ما الذي تريد كتابته؟', placeholder_en: 'What do you want to write?', icon: PenTool },
                                              ]
                                                },
                                                  {
                                                      id: 'editing', icon: Edit3, color: '#3B82F6',
                                                          label_ar: 'تحرير', label_en: 'Editing',
                                                              actions: [
                                                                    { type: 'rewrite', label_ar: 'إعادة صياغة', label_en: 'Rewrite', placeholder_ar: 'النص + التعليمات...', placeholder_en: 'Text + instructions...', icon: Edit3 },
                                                                          { type: 'compress', label_ar: 'اختصار', label_en: 'Compress', placeholder_ar: 'النص + الطول المستهدف...', placeholder_en: 'Text + target length...', icon: Edit3 },
                                                                                { type: 'expand', label_ar: 'توسيع', label_en: 'Expand', placeholder_ar: 'النص + النقاط الإضافية...', placeholder_en: 'Text + additional points...', icon: Edit3 },
                                                                                      { type: 'grammar', label_ar: 'تدقيق لغوي', label_en: 'Grammar', placeholder_ar: 'النص للمراجعة...', placeholder_en: 'Text to check...', icon: Edit3 },
                                                                                            { type: 'tone_shift', label_ar: 'تغيير النبرة', label_en: 'Tone Shift', placeholder_ar: 'النص + النبرة المستهدفة...', placeholder_en: 'Text + target tone...', icon: Edit3 },
                                                                                                ]
                                                                                                  },
                                                                                                    {
                                                                                                        id: 'seo', icon: Search, color: '#10B981',
                                                                                                            label_ar: 'SEO', label_en: 'SEO',
                                                                                                                actions: [
                                                                                                                      { type: 'seo_optimize', label_ar: 'تحسين SEO', label_en: 'Optimize', placeholder_ar: 'المحتوى + الكلمات المفتاحية...', placeholder_en: 'Content + keywords...', icon: TrendingUp },
                                                                                                                            { type: 'keywords', label_ar: 'كلمات مفتاحية', label_en: 'Keywords', placeholder_ar: 'الموضوع...', placeholder_en: 'Topic...', icon: Search },
                                                                                                                                  { type: 'meta', label_ar: 'وصف ميتا', label_en: 'Meta Description', placeholder_ar: 'المحتوى...', placeholder_en: 'Content...', icon: Search },
                                                                                                                                      ]
                                                                                                                                        },
                                                                                                                                          {
                                                                                                                                              id: 'ads', icon: TrendingUp, color: '#F59E0B',
                                                                                                                                                  label_ar: 'إعلانات', label_en: 'Ads',
                                                                                                                                                      actions: [
                                                                                                                                                            { type: 'ad_copy', label_ar: 'نص إعلاني', label_en: 'Ad Copy', placeholder_ar: 'المنتج + الميزات + الجمهور...', placeholder_en: 'Product + features + audience...', icon: TrendingUp },
                                                                                                                                                                ]
                                                                                                                                                                  },
                                                                                                                                                                    {
                                                                                                                                                                        id: 'story', icon: BookOpen, color: '#EC4899',
                                                                                                                                                                            label_ar: 'قصص', label_en: 'Story',
                                                                                                                                                                                actions: [
                                                                                                                                                                                      { type: 'character', label_ar: 'بناء شخصية', label_en: 'Build Character', placeholder_ar: 'الاسم + الدور + الصفات...', placeholder_en: 'Name + role + traits...', icon: BookOpen },
                                                                                                                                                                                            { type: 'dialogue', label_ar: 'حوار', label_en: 'Dialogue', placeholder_ar: 'الشخصيتين + الموقف...', placeholder_en: 'Characters + situation...', icon: MessageSquare },
                                                                                                                                                                                                ]
                                                                                                                                                                                                  },
                                                                                                                                                                                                    {
                                                                                                                                                                                                        id: 'research', icon: Brain, color: '#6366F1',
                                                                                                                                                                                                            label_ar: 'بحث', label_en: 'Research',
                                                                                                                                                                                                                actions: [
                                                                                                                                                                                                                      { type: 'research', label_ar: 'بحث', label_en: 'Research', placeholder_ar: 'الموضوع...', placeholder_en: 'Topic...', icon: Brain },
                                                                                                                                                                                                                            { type: 'fact_check', label_ar: 'تحقق', label_en: 'Fact Check', placeholder_ar: 'النص للتحقق...', placeholder_en: 'Text to verify...', icon: Brain },
                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                  ];
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                  const QUICK_ACTIONS = [
                                                                                                                                                                                                                                    { type: 'calendar', icon: Calendar, color: '#14B8A6', label_ar: 'تقويم محتوى', label_en: 'Calendar', placeholder_ar: 'الموضوع + المنصة...', placeholder_en: 'Topic + platform...' },
                                                                                                                                                                                                                                      { type: 'critic', icon: Sparkles, color: '#F97316', label_ar: 'مراجعة ناقد', label_en: 'Critic Review', placeholder_ar: 'النص للمراجعة...', placeholder_en: 'Text to review...' },
                                                                                                                                                                                                                                        { type: 'repurpose', icon: Filter, color: '#A855F7', label_ar: 'إعادة توظيف', label_en: 'Repurpose', placeholder_ar: 'المحتوى + الصيغة المصدر + الهدف...', placeholder_en: 'Content + source + target format...' },
                                                                                                                                                                                                                                        ];
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        interface BusinessMemory {
                                                                                                                                                                                                                                          id: string;
                                                                                                                                                                                                                                            content: string;
                                                                                                                                                                                                                                              importance: number;
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                              export default function ContentCreatorCapability() {
                                                                                                                                                                                                                                                const rtl = useRTL();
                                                                                                                                                                                                                                                  const [active, setActive] = useState(false);
                                                                                                                                                                                                                                                    const [inputText, setInputText] = useState('');
                                                                                                                                                                                                                                                      const [activeAction, setActiveAction] = useState<string | null>(null);
                                                                                                                                                                                                                                                        const [sessions, setSessions] = useState<CreatorSession[]>([]);
                                                                                                                                                                                                                                                          const [relevantMemories, setRelevantMemories] = useState<BusinessMemory[]>([]);
                                                                                                                                                                                                                                                            const [isProcessing, setIsProcessing] = useState(false);
                                                                                                                                                                                                                                                              const [lastResponse, setLastResponse] = useState('');
                                                                                                                                                                                                                                                                const [activeCategory, setActiveCategory] = useState<string>('writing');
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                  useEffect(() => {
                                                                                                                                                                                                                                                                      const unsub1 = EventBus.on('CAPABILITY_ACTIVATED', (payload: any) => {
                                                                                                                                                                                                                                                                            if (payload?.capability === 'content_creator') { setActive(true); loadCreatorContext(); }
                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                    const unsub2 = EventBus.on('CAPABILITY_DEACTIVATED', () => setActive(false));
                                                                                                                                                                                                                                                                                        const unsub3 = EventBus.on('WORKSPACE_CHANGE_REQUESTED', (payload: any) => {
                                                                                                                                                                                                                                                                                              if (payload?.workspace === 'content_creator') { setActive(true); loadCreatorContext(); }
                                                                                                                                                                                                                                                                                                    else if (payload?.workspace === null && active) { setActive(false); }
                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                            return () => { unsub1(); unsub2(); unsub3(); };
                                                                                                                                                                                                                                                                                                              }, [active]);
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                const loadCreatorContext = async () => {
                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                          const savedSessions = await memoryEngine.retrieveByType('learning', 20);
                                                                                                                                                                                                                                                                                                                                const creatorSessions = savedSessions
                                                                                                                                                                                                                                                                                                                                        .filter(m => m.relatedTo.some(r => ['content', 'creative', 'writing'].includes(r)))
                                                                                                                                                                                                                                                                                                                                                .map(m => ({
                                                                                                                                                                                                                                                                                                                                                          id: m.id, title: m.content.substring(0, 60),
                                                                                                                                                                                                                                                                                                                                                                    type: m.relatedTo.find(r => ['content', 'creative', 'writing'].includes(r)) || 'writing',
                                                                                                                                                                                                                                                                                                                                                                              content: m.content, timestamp: m.timestamp,
                                                                                                                                                                                                                                                                                                                                                                                      }));
                                                                                                                                                                                                                                                                                                                                                                                            if (creatorSessions.length > 0) setSessions(creatorSessions);
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                  const memories = await memoryEngine.retrieveByType('event', 10);
                                                                                                                                                                                                                                                                                                                                                                                                        const creatorMemories = memories.filter(m =>
                                                                                                                                                                                                                                                                                                                                                                                                                m.content.toLowerCase().includes('كتابة') || m.content.toLowerCase().includes('مقال') ||
                                                                                                                                                                                                                                                                                                                                                                                                                        m.content.toLowerCase().includes('write') || m.content.toLowerCase().includes('content')
                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                    setRelevantMemories(creatorMemories.slice(0, 3).map(m => ({ id: m.id, content: m.content.substring(0, 120), importance: m.importance })));
                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (e) {}
                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                            const handleQuickAction = async (actionType: string, placeholder?: string) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!inputText.trim() || isProcessing) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    setActiveAction(actionType);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        setIsProcessing(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            setLastResponse('');
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const enhancedMessage = `${rtl.isRTL ? 'طلب إبداعي:' : 'Creative request:'} ${actionType}: ${inputText.trim()}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const result = await sendMessage(enhancedMessage, [], rtl.isRTL ? 'ar' : 'en');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const reply = result?.reply || (rtl.isRTL ? 'تمت المعالجة.' : 'Processed.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const newSession: CreatorSession = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id: Date.now().toString(), title: inputText.trim().substring(0, 60),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type: actionType, content: reply, timestamp: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setSessions(prev => [newSession, ...prev.slice(0, 14)]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setLastResponse(reply);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try { await memoryEngine.store('learning', inputText.trim(), 60, 'focused', ['content', actionType]); } catch (e) {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setLastResponse(rtl.isRTL ? 'حدث خطأ. حاول مرة أخرى.' : 'An error occurred. Please try again.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setIsProcessing(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setInputText('');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!active) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const timer = setTimeout(async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const decision = await consciousnessCoordinator.decide('creative', 'focused');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (decision.action === 'check_in') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          EventBus.emit('TWIN_SPEAK', { phrase: rtl.isRTL ? 'هل نبدع شيئاً جديداً؟' : 'Shall we create something new?', tone: 'gentle' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (e) {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, 10000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return () => clearTimeout(timer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }, [active]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const handleDeactivate = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EventBus.emit('CAPABILITY_DEACTIVATED', { capability: 'content_creator', timestamp: Date.now() });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            capabilityResolver.deactivate();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ENDOFFILE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              echo "✅ ContentCreatorCapability_part1.tsx"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional

router = APIRouter(prefix="/api/image-lab", tags=["image-lab"])

class ImageRequest(BaseModel):
    user_id: str = "test123"
    prompt: str
    style: str = "realistic"
    lighting: str = ""
    camera: str = ""
    negative: str = ""
    language: str = "ar"

class EnhanceRequest(BaseModel):
    user_id: str; prompt: str; language: str = "ar"

class AnalyzeRequest(BaseModel):
    user_id: str; image_base64: str; language: str = "ar"

class EditRequest(BaseModel):
    user_id: str; operation: str; image_base64: str

class DashboardRequest(BaseModel):
    user_id: str; lang: str = "ar"

@router.post("/generate")
async def generate(req: ImageRequest):
    try:
        from app.features.image_lab.image_orchestrator import image_lab
        return await image_lab.generate(req.user_id, req.prompt, req.style, req.lighting, req.camera, req.negative, req.language)
    except Exception as e: raise HTTPException(500, str(e))

@router.post("/enhance-prompt")
async def enhance_prompt(req: EnhanceRequest):
    from app.features.image_lab.image_orchestrator import image_lab
    return await image_lab.enhance_prompt(req.user_id, req.prompt)

@router.post("/analyze")
async def analyze(req: AnalyzeRequest):
    from app.features.image_lab.image_orchestrator import image_lab
    return await image_lab.analyze_image(req.image_base64, req.language)

@router.post("/edit")
async def edit(req: EditRequest):
    from app.features.image_lab.image_orchestrator import image_lab
    return await image_lab.edit_image(req.operation, req.image_base64)

@router.get("/dashboard/{user_id}")
async def dashboard(user_id: str, lang: str = "ar"):
    from app.features.image_lab.image_orchestrator import image_lab
    return await image_lab.get_dashboard(user_id, lang)
